from . import risk_disaster
from . import risk_action
from . import risk_cause
from . import risk_impact
from . import risk_miltigation
from . import stock_disaster
from . import risk_config
from . import campany_cantact
from . import hr_employee
from . import external_ressource_company
from . import wizard
from . import whatsapp
from . import res_company
from . import risk_activity
from . import super_observer_action
from . import external_ressource
from . import risk_project